version: '3'

services:
  api:
    build: ./
    restart: always
    container_name: personal-office-api
    ports:
      - "5005:8080"
    environment:
      - TZ=Europe/Moscow
      - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ./Logs:/app/Logs
  redis:
    image: redis
    restart: always
    container_name: personal-office-redis
    ports:
      - "6379:6379"